### ISSUE TITLE
Markdown image brackets (missmatch)

### ISSUE THREAD

**Issue by generic-user** [philippotto/Sublime-BracketGuard#10]
Hi, when writing markdown, the bracketguard highlights a bracket as error, while it is not. Here is an example:

```
![ example](img/example.png)
```

![example](https://lh4.googleusercontent.com/-SgeXhRPQYKI/VS4d4F6t7PI/AAAAAAAAFng/07uZmdLQ7bM/s0/2015-04-15_10-14-22.png)

**Comment by philippotto** [comment]
Hi @generic-user! Thanks for filing this issue. It should be fixed with the new release :)

**Comment by generic-user** [comment]
Wow, that was fast, thanks!
